### ISSUE TITLE
Compile issue: looking for jni.h under /usr/share/java

### ISSUE THREAD

**Issue by borjam** [netxms/netxms#12]
Hi,

I've downloaded 2.2.17 from the website. Trying to compile on FreeBSD, configure aborts:

```
checking jni.h usability... no
checking jni.h presence... no
checking for jni.h... no
configure: error: *** Cannot find jni.h - check your JDK installation ***
```

My configure invocation was:

`./configure --with-server --with-snmp --with-mysql --sysconfdir=/usr/local/etc/netxms --sharedstatedir=/var/db/netxms --localstatedir=/var/db/netxms --with-jdk --includedir=/usr/local/openjdk8/include`

 Checking config.log it searched for jni.h under /usr/share/java, for which I don't see any override option. In order to compile 2.2.16 I remember I set the --includedir variable pointing to the openjdk8 installation but it seems to be ignored on 2.2.17. Or I am terribly thick this morning!

**Comment by 2128506** [comment]
Try to use --with-jdk=/usr/local/openjdk8 instead (do not specify includedir).

**Comment by borjam** [comment]
So yes, I was thick indeed.

It compiled, thank you!
