### ISSUE TITLE
Doesn't Support Arm. Make that obvious.

### ISSUE THREAD

**Issue by Az-Neter** [netxms/netxms#129]
It would've been nice to know this software doesn't actually support arm devices before spending a not-insignificant amount of time thinking otherwise given the prevalence of Debian arm devices.

Fix your readme to reflect the fact that you neglect your most likely user base, so other people aren't stuck wasting their time as I just did.

Otherwise, why is apt telling me your arm64 package repository doesn't support arm64?

**Comment by alkk** [comment]
ARM architecture is fully supported, but we currently do not provide deb packages (it require changes in our release process). You can compile them yourself for now, scripts are publicly available at https://github.com/netxms/packages-deb.
