### ISSUE TITLE
In ui, passwords are visible

### ISSUE THREAD

**Issue by Varik001** [netxms/netxms#3]
For us it is mayor security issue.
All password should by hidden from eye.

![passwords are visible](https://user-images.githubusercontent.com/45542217/50212342-7fb9e880-0383-11e9-827d-a98f44bce596.PNG)

![passwords are visible2](https://user-images.githubusercontent.com/45542217/50212343-7fb9e880-0383-11e9-9508-e2abf0aa2a3d.PNG)

**Comment by 2128506** [comment]
Fixed in 4.x
