### ISSUE TITLE
When saving script in NetXMS 3.7.116, it often will indicate it has saved, but isn't

### ISSUE THREAD

**Issue by Zebble** [netxms/netxms#51]
Actions:

- Edit Hook::ConfigurationPoll
- Save Changes
- Hit "Refresh" and changes will often be reverted.

To workaround:

- Rename Hook::ConfigurationPoll to something else.
- Change the script and save it.  Refresh, and it doesn't revert.
- Rename back to Hook::ConfigurationPoll
-

**Comment by Zebble** [comment]
Just updated to 3.7.130 and having the same issue.

**Comment by Zebble** [comment]
Just tested 3.8.120 and this appears to be working reliably.  I don't see any notes in the latest commits that would indicate this has been fixed or is related to this issue, so not sure if i'm just "lucky" or if this has really been fixed.

**Comment by 2128506** [comment]
Let's close it for now, if you ever encounter it again please re-open this issue.
