### ISSUE TITLE
After upgrade from 3.7 to 3.8, my web service dci polling has been stopped.

### ISSUE THREAD

**Issue by tanero** [netxms/netxms#53]
- Web service proxy function in core agent now disabled by default
- Only HTTP and HTTPS are allowed in web service URLs

Please could you explain, how can I enable web service check from agent ?

 I wonder if it is config changed issue ?

**Comment by 2128506** [comment]
You should add to config file of your agent line

`EnableWebServiceProxy = yes`

This change was done for improving security. Before 3.8 read access to agent allows you to do port scan (by requesting URLs with different service types and port numbers) and even local file access (using file:// URLs).
