### ISSUE TITLE
Vulnerability-The password in WEBUI is visible

### ISSUE THREAD

**Issue by HYWZ36** [netxms/netxms#54]
This vulnerability exposes the account password, so that the attacker can see the network internal host information, has a great harm.
When I looked at the data packets analyzed for the login site【http://192.168.163.133:8080/nxmc-clarity】, I found that the password was presented in clear text in JSON, as follows【admin:admin,password:test2】:
![image](https://user-images.githubusercontent.com/27775281/114161763-04691000-995b-11eb-9c18-36fffa62a095.png)

**Comment by alkk** [comment]
It's not a bug - you should never use clear-text HTTP. Configure encryption (HTTPS) on the container level (Tomcat, Jetty - whatever you are using).

**Comment by HYWZ36** [comment]
ok, sorry.

> It's not a bug - you should never use clear-text HTTP. Configure encryption (HTTPS) on the container level (Tomcat, Jetty - whatever you are using).

ok,sorry
