### ISSUE TITLE
CAS Validation URL

### ISSUE THREAD

**Issue by emris** [netxms/netxms#58]
aloha,

I think there is a typo in master/src/server/core/cas_validator.cpp line 281
->   if (snprintf(full_request, 4096, "GET %s?ticket=%s&service=%s HTTP/1.0\n\n", s_validateURL, ticket, s_service) >= 4096)

It should be "HTTP/1.0\r\n" or just "HTTP/1.0"

Apache Server is giving me a 400 error because of "HTTP/1.0\n"
-> "GET /cas/serviceValidate?ticket=ST-10159-jh3DJSRUbD59ciOtDxEuVFq3XCU-casdev&service=https://test.server.xyz/mon/nxmc-clarity HTTP/1.0\n" 400 4819 "-" "-"

Thank You for the best monitoring Software ever :D

**Comment by 2128506** [comment]
There should be empty line after GET to indicate than no more headers will come. However, to strictly follow protocol standard it should be \r\n\r\n. It is strange that \n appears literally in what seems to be web service access log, but maybe LF character is converted to this form for logging.
I've changed \n\n to \r\n\r\n in master branch as well as stable-3.9 and stable-3.8. Next release will contain this fix.

**Comment by emris** [comment]
After latest Update CAS is working now 👍
