### ISSUE TITLE
Net.Interface raw value does not change, delta is always 0 on FreeBSD-13

### ISSUE THREAD

**Issue by kaanlab** [netxms/netxms#59]
Net.Interface.Bytes(In/Out)64  raw value does not change, delta is always 0. 
[This is the description of the error from the netxms forum](https://www.netxms.org/forum/general-support/error-when-install-netxms-3-8-314-from-source-on-freebsd-13/)
I try to update agent to last version but it did not help.
` 13.0-RELEASE FreeBSD 13.0-RELEASE`
` NetXMS Core Agent Version 3.8.382 Build 3.8-382-gc0100d1389 (UNICODE) `

**Comment by 2128506** [comment]
Fixed by recent commits in master, stable-3.9, and stable-3.8
