### ISSUE TITLE
Unknown Object Attribute and Method

### ISSUE THREAD

**Issue by EclipseKnight** [netxms/netxms#85]
I'm currently learning NXSL to write scripts for executing ssh commands to nodes but have immediately run into issues that I'm unable to pinpoint the issue based on their documentation here: [https://www.netxms.org/documentation/nxsl-latest/#_introduction](https://www.netxms.org/documentation/nxsl-latest/#_introductionl)

I've left a post on the support forum outlining my issue and further information on what I was able to verify.
[https://www.netxms.org/forum/general-support/unknown-object-attribute-and-method/](https://www.netxms.org/forum/general-support/unknown-object-attribute-and-method/)

```
1 sub main() {
2 	node = Objects.FindNodeByIPAddress($1, null);
3
4	if (node == NULL) {
5		println("Error: node not found.");
6    }
7
8	//println(node->name);
9   println(node->executeSSHCommand("ip address print"));
10}
```

When I try to execute the code above, it says "Error 30 in line 9: Unknown object's method" claiming the executeSSHCommand method doesn't exist, yet based on Node documentation is does. 

When commenting that line out and uncommenting line 8, it says the attribute doesn't exist. 
However, in documentation, it does. 

I found that the node variable is a String based on the classof(node) and typeof(node) methods. It seems all the FindNode methods are returning strings instead of instances of Node and I have verified this.

My 2nd follow up post on the forum
[https://www.netxms.org/forum/index.php?msg=32315](https://www.netxms.org/forum/index.php?msg=32315)

I'm running the follow:

Server version: 4.3.2 (build 4.3-374-g4f45f9ba5c)
Java version: 11.0.10
JVM: OpenJDK 64-Bit Server VM 11.0.10+9

**Comment by 2128506** [comment]
FindNodeByIPAddress is a function, so you should not add "Objects." in front of it. Dot is string concatenation operation in NXSL (we plan to change that in 5.0, but that's another story) - so Objects . FindNodeByIPAddress concatenates null value converted to empty string from non-existent variable "Objects" with object returned by FindNodeByIPAddress converted to string - so result is a string.
Correct script will be something like this:
```
node = FindNodeByIPAddress($1, null);
if (node == NULL) {
   println("Error: node not found.");
   return;
}
println(node->name);
println(node->executeSSHCommand("ip address print"));
```
