### ISSUE TITLE
Wrong SNMP OID from device after full configuration

### ISSUE THREAD

**Issue by CapNem0** [netxms/netxms#89]
Несколько странные результаты  опроса сервером конифгруации устройства. 
Имеем  около 50  QTECH QSW-4610T с разынм количеством портов. После опроса получаем вот такой OID.

SNMP Object ID=.1.3.6.1.4.1.27514.1.1.1.480 

![Screenshot 2023-07-01 at 10 10 04](https://github.com/netxms/netxms/assets/1137679/4413ed4e-74a1-490e-91a0-3b18ab1bd593)

При ручном опросе говорят идите в пеший маршрут 
```
nxadmin@netxms4:~$ snmpwalk -c public -v 2c 10.102.7.1 .1.3.6.1.4.1.27514.1.1
iso.3.6.1.4.1.27514.1.1 = No Such Object available on this agent at this OID
```

В миб файле такого тоже нет. Происходит по естественно по всем коммутаторам. 

[MIB file ](https://ftp.qtech.ru/Switch/Access/QSW-4610/MIB's/QSW-4610_Qtech_private_2.1.29.mib )
Где порылась собака? 

PS: Пробовал ручками поменять OID в базе nodes.snmp_oid  - не работает.

**Comment by CapNem0** [comment]
Так, можно закрывать тикет. Ошибка в самом устройстве видимо
`nxadmin@netxms4:~$ snmpwalk -c public -v 2c 10.102.7.1 .1.3.6.1.2.1.1
iso.3.6.1.2.1.1.1.0 = STRING: "Device: QSW-4610-52T-AC
 SoftWare Version 8.2.1.151
 BootRom Version 2011.12.26
 HardWare Version 1.0.2
  Serial No.:5793150820220176
 Copyright (C) 2021 by QTECH LLC
 All rights reserved
"
iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.27514.1.1.1.480
iso.3.6.1.2.1.1.3.0 = Timeticks: (500908100) 57 days, 23:24:41.00
iso.3.6.1.2.1.1.4.0 = STRING: "Maxim Khludov"
iso.3.6.1.2.1.1.5.0 = STRING: "ufa-swt-qsw52-3"
iso.3.6.1.2.1.1.6.0 = STRING: "bld-2-floor-5-server-room"
iso.3.6.1.2.1.1.7.0 = INTEGER: 6
iso.3.6.1.2.1.1.8.0 = Timeticks: (1700) 0:00:17.00
iso.3.6.1.2.1.1.9.1.2.1 = OID: iso.3.6.1.2.1.1
iso.3.6.1.2.1.1.9.1.2.2 = OID: iso.3.6.1.2.1.2
iso.3.6.1.2.1.1.9.1.2.3 = OID: iso.3.6.1.2.1.4
iso.3.6.1.2.1.1.9.1.2.4 = OID: iso.3.6.1.2.1.5
iso.3.6.1.2.1.1.9.1.2.5 = OID: iso.3.6.1.2.1.17
iso.3.6.1.2.1.1.9.1.2.6 = OID: iso.3.6.1.2.1.31
iso.3.6.1.2.1.1.9.1.2.7 = OID: iso.3.6.1.2.1.14


`
Вопрос ка лечить ?

**Comment by 2128506** [comment]
Even if device reports wrong sysObjectId - this should not affect server operation in any way except (possibly) driver selection. If there is matching driver selection can be forced by setting custom attribute "snmp.driver" to driver name.
